### ISSUE TITLE
 WalletHandler is not a constructor

### ISSUE THREAD

**Issue by yashvadhvani** [johnjayasingh/sawtooth-boilerplate#1]
I am able to use intkey_handler but when i use this it shwos the error  WalletHandler is not a constructor. Please help me with that

**Comment by johnjayasingh** [comment]
I have updated the code with a fix. module.exports was missing in wallet_handler.

**Comment by yashvadhvani** [comment]
There is another error sir 
```
constructor(){
        super(FAMILY_NAME,[VERSION],NAMESPACE)
    }
```
Constructor should be this way Version expects an array it almost took a day for me to understand
